<?php

namespace Fabiang\Common\SwitchDatabase;

use PHPUnit\Framework\TestCase;
use Prophecy\PhpUnit\ProphecyTrait;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-12-09 at 13:28:02.
 *
 * @coversDefaultClass Fabiang\Common\SwitchDatabase\Module
 */
final class ModuleTest extends TestCase
{

    use ProphecyTrait;

    /**
     * @var Module
     */
    private $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp(): void
    {
        $this->object = new Module;
    }

    /**
     * @covers ::getConfig
     */
    public function testGetConfig()
    {
        $config = $this->object->getConfig();
        $this->assertIsArray($config);
        $this->assertArrayHasKey('switch-database', $config);
    }

    /**
     * @covers ::getModuleDependencies
     */
    public function testGetModuleDependencies()
    {
        $this->assertSame(['DoctrineORMModule'], $this->object->getModuleDependencies());
    }

}
